name: Check Markdown and Examples
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/setup-node@v3.6.0
      - uses: actions/checkout@v3
      - run: |
          npm install
          npm test
