name: Check Markdown and Examples
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v3.0.2
      - run: |
          npm install
          npm test
